/** Query key factory: one place to reason about caching and invalidation. */
export const qk = {
  me: ['me'] as const,
  settings: ['settings'] as const,
  providers: ['auth', 'providers'] as const,
  products: (query: object) => ['products', query] as const,
  product: (slug: string) => ['product', slug] as const,
  reviews: (productId: string) => ['reviews', productId] as const,
  cartQuote: (payload: object) => ['cart', 'quote', payload] as const,
  favorites: ['favorites'] as const,
  favoriteIds: ['favorites', 'ids'] as const,
  addresses: ['addresses'] as const,
  sessions: ['sessions'] as const,
  orders: (query: object) => ['orders', 'list', query] as const,
  order: (id: string) => ['orders', 'detail', id] as const,
  admin: {
    all: ['admin'] as const,
    dashboard: (days: number) => ['admin', 'dashboard', days] as const,
    products: (query: object) => ['admin', 'products', query] as const,
    product: (id: string) => ['admin', 'product', id] as const,
    categories: ['admin', 'categories'] as const,
    ingredients: ['admin', 'ingredients'] as const,
    crusts: ['admin', 'crusts'] as const,
    orders: (query: object) => ['admin', 'orders', query] as const,
    order: (id: string) => ['admin', 'order', id] as const,
    users: (query: object) => ['admin', 'users', query] as const,
    promo: (query: object) => ['admin', 'promo', query] as const,
    reviews: (query: object) => ['admin', 'reviews', query] as const,
    audit: (query: object) => ['admin', 'audit', query] as const,
    settings: ['admin', 'settings'] as const,
  },
};
